server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ParcelOrderDb
    username: root
    password: 2772
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#  application:
#    name: ORDER-SERVICE
#
#  config:
#    import: configserver:http://localhost:9296